### ISSUE TITLE
剧场版支持

### ISSUE THREAD

**Issue by arition** [bangumi-data/bangumi-data#1]
是否有计划提供剧场版/OVA支持？
剧场版的话，我想首先需要在所有的条目当中加一个AnimeType，用于标识这个条目是TV/OVA/剧场版。剧场版的话，应该还需要同时提供上映日期和BD发售日期。
数据源的话可以先参考[萌娘百科](https://zh.moegirl.org/%E6%97%A5%E6%9C%AC2015%E5%B9%B4%E5%89%A7%E5%9C%BA%E7%89%88%E5%8A%A8%E7%94%BB)

**Comment by weizhenye** [comment]
**Bangumi** data 的数据主体应当是番组吧，虽然起名时可能没想这么多，不过当前的数据类型都是番组。
目前数据主要是番组相关的站点，尤其是放送站点，像《言叶之庭》这样有网站放送的剧场版可能不多吧。
你有具体的使用场景？

**Comment by arition** [comment]
恩，我需要使用剧场版/OVA数据。我主要是想讨论一下数据结构和格式的问题，可以的话把剧场版的信息也加入Bangumi
data。如果你觉得放在这里不合适，我就自己另外fork一个出来做了。
至于名字，名字什么的也无所谓吧，bangumi.tv也有剧场版和ova的信息。

**Comment by wxt2005** [comment]
这个项目主要是为了收集放送站点及一些相关的资讯站点，番组的元数据反而算是附带的内容了。对于几乎没有网络放送的剧场版/OVA来说，可能确实不太合适。
当然也不是说完全不行。如果要放的话，可以分开一个 `movie` 的数组，专门用来放剧场版/OVA（个人认为 OVA 也算是一种特殊的剧场版），其中再用类似 `type` 的字段来区分具体是剧场版还是 OVA。
@weizhenye 你觉得如何？

**Comment by arition** [comment]
我觉得ova和剧场版还是分开比较好。ova只有发售日期，而剧场版有上映日期和发售日期，这是不同的。

**Comment by weizhenye** [comment]
@arition 你需要的是什么数据？剧场版的元数据吗？放送时间之类的？还是相关站点数据？网络放送的链接数据之类的？
@wxt2005 另外开个数组是和 `dist/data.json` 平级的数组吗？这样基本变成另一个项目了吧。

我觉得如果是针对剧场版相关站点的数据，如果有（可能就 B 站有一些），可以考虑对原数据进行扩展；但如果单纯的就放些元数据，感觉这个和目前定位差距比较大了，不应该在这个项目里维护。

**Comment by arition** [comment]
其实我需要的是剧场版/OVA的名字，上映时间，发售时间和bangumi的地址。其实我觉得能扩展些数据总归是好的。如果你觉得不合适的话我还是自己fork一个出来做。
