### ISSUE TITLE
能显示封面就好了

### ISSUE THREAD

**Issue by 610364023** [bangumi-data/bangumi-data#101]

**Comment by swearl** [comment]
有bangumi id就可以直接用bangumi api拿到

**Comment by weizhenye** [comment]
显示是指哪？bangumi-data 只提供数据，没有提供展示。如果是指对应的使用 bangumi-data 的服务的展示，那 issue 提到对应的服务。

我想 bangumi-data 本身是不应该维护封面数据的，meta 信息不应受特定服务可靠性的影响（即不应该是网址），直接管理图片文件更不合适。
