### ISSUE TITLE
关于长期连载动画的放送时间变更

### ISSUE THREAD

**Issue by wxt2005** [bangumi-data/bangumi-data#106]
例如类似《名侦探柯南》TV版这样的情况，放送开始是日本时间的1996-01-08 19:30（周一），但是在2009年调整成了日本时间的周六晚上18:00（参考：[名探偵コナン (アニメ)](https://ja.wikipedia.org/wiki/名探偵コナン_(アニメ))），该如何在数据中体现？

我现在能想到的解决方案有两种：

1. 将不同放送时间段播出的部分视为不同的数据条目，这样在不同年份的数据中会存在标题相同但放送开始时间（begin）不同的番组。问题在于是否要加上类似版本的字段，用来标明这些数据属于同一个番组。
2. begin字段不变，在条目数据中增加放送日期调整历史的可选数组字段，将每次的日期变更列出。这个字段也可以同时应用于各放送站点的播放时间调整。

@weizhenye 你怎么看？

**Comment by weizhenye** [comment]
想起还没从 bangumi-list 里分出来的时候是有 week 字段的，当时觉得没用，现在看来应该是个如何描述非规则放送的问题。

当前默认每集放送时间是 begin 按周间隔到 end，要说例外情况其实有不少：
* 长篇调整放送时间
* 停播
* 两集连播
* 日播（[终物语（下）](https://bgm.tv/subject/175596)）
* 月播（[刀语](https://bgm.tv/subject/3471)）
* 后几集无规则播（[天才麻将少女 阿知贺篇](https://bgm.tv/subject/24165)）
* OVA 类无规则
* Web 类一次性放出、分段放出

感觉如果要完整解决这个问题，那就是 cal.syoboi.jp 了，方向上不太合理。可能得先明确下在 bangumi-data 中寻求放送时间，要做到什么程度。

**Comment by wxt2005** [comment]
现在数据中的begin，是一个拿来描述放送开始时间的字段，并不完全等同于每周的放送时间，只不过大部分时间是重叠的，现在看来是不太足够了。其实我觉得做成cal.syoboi.jp那样的数据丰富程度没什么问题，只不过以我们的精力来说不太现实，也没什么必要。

对于你提到的这些例外情况，我是这么看的：

* 长篇调整放送时间：也不一定是长篇，只不过常规动画较少出现档期变化。应该要有字段来记录最新的放送时间。可以讨论下是接着拿绝对时间（变更开始的时间）来记录，还是单纯记录周天和时间；以及是要记录历史变更历史，还是直接修改到最新数据（个人推荐前者，这样可以把一个时效性数据沉淀为一个历史性数据）。
* 停播：倾向于暂时不处理。并不是说没用，而是感觉暂时没精力管这块。另外出现这种情况较少（虽然今年就碰上了新冠XD）。
* 连播：大部分情况下不影响放送时间，可以不处理。
* 日播：考虑加入放送周期的字段。
* 月播：同上。
* 无规则播：暂时不处理，这种情况需要人肉发现，估计没有精力管。如果将来打算处理，走放送时间调整的方案。
* OVA：这个暂时没啥好方案。对于分卷发售的OVA，可以考虑每一卷单独放一条数据（类似剧场版）。
* Web 类一次性放出：放送周期可以添加相应分类。分段放出不太清楚是个什么模式，可否举个例子？

综上，我个人的方案是：增加一个枚举字段描述放送周期，默认为按周放送；增加一个可选列表字段存放放送时间变更的历史。

**Comment by weizhenye** [comment]
Web 分段放送例如 [BNA](https://zh.wikipedia.org/wiki/%E5%8A%A8%E7%89%A9%E6%96%B0%E4%B8%96%E4%BB%A3_BNA)，先放 1-6 集，后放 7-12 集，不过在 [Bangumi 上](https://bgm.tv/subject/285905)是按电视台时间来的。

在 bangumi-data 中怎样算作一个条目，我觉得应该和各个信息站点保持一致，Bangumi、MyAnimeList 上应该要一一对应上。因放送时间而拆成多个条目的话，感觉维护和使用上都会比较麻烦。

按我能想到的大多数情况，放送时间应该是个时效性数据，给已完结番剧或已播放剧集描述放送时间，其实没什么实际使用场景吧。结合我们实际的维护情况，停播这种一般突发性的是来不及更新维护的。

但是要描述的话，我觉得还是要通用一点。cal.syoboi.jp 是记录每集的放送时间，能够满足我们需要的周期和历史，我们可以用「压缩」的方式来描述每集放送时间，仅记录有变更的集数，也就是你的方案里两个字段结合一下：

```js
{
  episodes: [
    { 
      // 第几集
      episode: Number, 
      // 该集放送时间
      begin: Date, 
      // 从该集开始的放送间隔（天数），这个值设置后影响后面所有集数，直到被下一个设置覆盖，或直到完结
      interval: Number 
    },
  ]
}
```

这样的话，以上各个情况应该都能描述出来了，正常的大多数番剧都不需要描述这个字段。例如：

播放时间调整：
```js
{
  episodes: [
    // 表示从 100 开始放送时间调整为 begin，interval 默认为 7 不变
    { episode: 100, begin: '2020-01-01T00:00:00.000Z' }
  ]
}
```

停播（[某科学的超电磁炮T](https://bgm.tv/subject/262940)）：
```js
{
  episodes: [
    { episode: 6, begin: '2020-02-14T13:00:00.000Z', interval: 14 },
    { episode: 7, begin: '2020-02-28T13:00:00.000Z', interval: 21 },
    { episode: 8, begin: '2020-03-20T13:00:00.000Z', interval: 7 },
    // 8, 9, 10, 11, 12 的间隔都是 7
    { episode: 12, begin: '2020-04-17T13:00:00.000Z', interval: 14 },
    // 这里 13 集 2020-05-01，间隔也是 14，继承前面的值，不需要描述
    { episode: 14, begin: '2020-05-15T13:00:00.000Z', interval: 7 },
    { episode: 15, begin: '2020-05-22T13:00:00.000Z', interval: 63 },
    { episode: 16, begin: '2020-07-24T13:00:00.000Z', interval: 7 },
  ]
}
```

一次性放送（[恶魔人 crybaby](https://bgm.tv/subject/211311)）：
```js
{
  episodes: [
    { episode: 1, begin: '2018-01-05T16:00:00.000Z', interval: 0 }
  ]
}
```

**Comment by wxt2005** [comment]
我觉得你的方案不错，更加通用。不过我在想如果这样的话，是不是`interval`这个字段直接允许在条目数据里使用会比较好，这样对于日更月更、OVA以及一次性放送等情况的片子，一开始就能进行描述。毕竟调整放送时间并不是经常出现的情况。

**Comment by weizhenye** [comment]
我看到过的日更其实不是简单的一日一集，像终物语（下）是第一天 4 集第二天 3 集；月更目前我知道的只有刀语；OVA 的话其实没什么固定间隔，大部分无规则的；好像只有一次性放送能用到。

**Comment by wxt2005** [comment]
确实情况不多，不过可以先确定好。毕竟也不知道以后会咋样，当年开始搞bangumi-list的时候，哪想到还会出现Netflix这种模式（

**Comment by weizhenye** [comment]
嗯，可以吧，新增的 interval 和 episodes 都是选填，`item.begin` 和 `item.interval` 就代表 `{ episode: 1 }`。

episodes 里 begin 必填，interval 选填。episode 是否可以省略？

**Comment by wxt2005** [comment]
`episodes.episode`还是必填吧，毕竟都是按集来调整，看起来清晰些。选填也节省不了多少空间。

**Comment by weizhenye** [comment]
主要担心集数出现 x.5 之类的，以及长篇的集数比较难考证，柯南的变更我看维基没看出具体是哪集。不过从 cal.syoboi.jp 还是能找到的，必填应该不会有太大问题吧。

**Comment by wxt2005** [comment]
你这么一说确实……但如果`episode`是选填的话，这个字段叫`episodes`就有点诡异。要不要做成字符串类型的？

**Comment by weizhenye** [comment]
我现在想想 `episode` 必填没问题吧。

Bangumi.tv 上集数就是数字类型的，极端情况会用 [7.1、7.2](https://bgm.tv/subject/262940) 之类的表示，非正常集数大不了不记录，只记录正片的时间就好了。

长篇的话就那几部，新番剧出现要描述的时候，应该都是可查证的。

**Comment by wxt2005** [comment]
实际用柯南试了一下，在放送站点比较多的情况下感觉有点啰嗦，其它应该还好。

```json
{
    "title": "名探偵コナン",
    "titleTranslate": {
      "zh-Hans": [
        "名侦探柯南"
      ],
      "en": [
        "Detective Conan",
        "Case Closed"
      ]
    },
    "type": "tv",
    "lang": "ja",
    "officialSite": "http://www.ytv.co.jp/conan/",
    "begin": "1996-01-08T10:30:00.000Z",
    "end": "",
    "episodes": [
      {
        "episode": 515,
        "begin": "2008-10-20T10:00:00.000Z"
      },
      {
        "episode": 530,
        "begin": "2009-04-18T09:00:00.000Z"
      }
    ],
    "sites": [
      {
        "site": "iqiyi",
        "id": "a_19rrhc0gyd",
        "begin": "2016-09-28T12:45:45.000Z",
        "episodes": [
          {
            "episode": 530,
            "begin": "2009-04-18T11:30:00.000Z"
          }
        ]
      },
      {
        "site": "qq",
        "id": "5/53q0eh78q97e4d1",
        "begin": "1996-01-13T11:30:00.000Z",
        "episodes": [
          {
            "episode": 530,
            "begin": "2009-04-18T11:30:00.000Z"
          }
        ]
      },
      {
        "site": "pptv",
        "id": "ac24Np4EdLIVkics",
        "begin": "1996-01-13T11:30:00.000Z",
        "episodes": [
          {
            "episode": 530,
            "begin": "2009-04-18T11:30:00.000Z"
          }
        ]
      },
      {
        "site": "youku",
        "id": "cc003400962411de83b1",
        "begin": "2012-05-10T10:15:24.000Z",
        "episodes": [
          {
            "episode": 530,
            "begin": "2009-04-18T11:30:00.000Z"
          }
        ]
      },
      {
        "site": "bangumi",
        "id": "899"
      },
      {
        "site": "netflix",
        "id": "80090370",
        "begin": "2016-01-01T08:00:00.000Z"
      },
      {
        "site": "bilibili",
        "id": "28228775",
        "begin": "2020-04-29T16:00:00.000Z",
        "episodes": [
          {
            "episode": 530,
            "begin": "2009-04-18T11:30:00.000Z"
          }
        ]
      }
    ]
  }
```

**Comment by weizhenye** [comment]
呃，sites 里面也需要这么描述吗，episodes 里 begin 比外面 begin 还早，已经不是真实数据了吧。我觉得 sites 里面不应该这么搞，这个没法实际操作的。

**Comment by wxt2005** [comment]
电视放送的时间变更往往也会伴随着网络放送的时间变更，所以肯定得一起变。不用这种格式的话，那要么就是直接更新begin（语义会产生歧义），要么加个字段专门拿来描述最新的放送时间了

**Comment by weizhenye** [comment]
从长远看，我觉得 sites 里的 begin 是不太合适的。番剧的 begin 还承载了指明哪年哪季的作用，这个是番剧本身的属性，而 sites begin 则不需要提供这个信息。一般站点页面上都是描述每周几什么时间更新一集，需要描述的是 begin 的 time 部分，和星期。  
  
但是对于 sites 的放送时间，我还是同样的观点，它是一个时效性数据，过了这个时间就没有什么价值了。比如某站上了一部老番，它的 begin 和番剧原始的年、季、星期、时间都没什么关系，begin、episodes、interval 字段如果在那里，是可以描述出来，但这种情况描述出来是没有意义的。站点放送时间比番剧本身的放送时间更不稳定，放到一半和谐下架了、国内出资网站放送比日本 TV 还早、版权到期了、网站倒闭了，总有想不到的情况。
  
我们对站点放送时间的需求，是为**正在放送**的番剧，提供该站点当前的放送**星期**和**时间**。从定义上，sites begin 是指该站首次放送该番剧的时间，在站点放送时间没有变更的情况下，sites begin 可以满足这个需求。

那现在实际情况中，正在放送的这些番剧中，有存在站点放送时间变化的情况吗？如果没有的话，我觉得是不用考虑这个情况的。柯南的 sites begin 估计是当时手写的，明确 time 部分后直接把 date 复制过来了，sites begin 是 1996 肯定不对的，在 2009 之后，各站点的放送时间不一定有变吧。

综上，我的想法：
* 只关心正在放送集数的站点放送时间
* 当前正在放送的番剧中
	* 如果不存在站点放送时间变化的情况，那就先不管。个人感觉是这个情况
	* 如果存在，那就直接改 begin 字段的值，虽然不合定义，但合实际使用需求
* 在规划下个版本（`0.4`）时，删除 sites begin ，使用新的字段和形式来描述

**Comment by wxt2005** [comment]
就像你说的，站点放送时间只在连载时有用，连载结束了，起码对我们这个项目来说，就没什么意义了。所以直接更新到最新我没有意见，那像柯南这种情况，其实直接改到最新就行了。0.4的时候，可以考虑直接使用weekday和time来描述，像现在这样用第一集的播放时间确实容易造成误解。
那对于柯南这个情况，我就暂且直接更新一下site.begin了，别的变更我们放到0.4来讨论？

**Comment by weizhenye** [comment]
番剧放送时间，无变更历史，只保留最新的状态，我觉得 OK。但新的字段、形式需要明确上面提到的各类情况要怎么处理，比如一次性放送的，weekday 无意义，该怎么描述。

**Comment by weizhenye** [comment]
[ISO 8601](https://zh.wikipedia.org/wiki/ISO_8601) 里倒是有对循环时间的规范，如 `R/2009-04-18T09:00:00.000Z/P1W` 表示从 `2009-04-18T09:00:00.000Z` 开始 1 星期 1 循环，一次性放送的话大概可以是 `R/2018-01-05T16:00:00.000Z/P0D`。这样的话解析稍微麻烦点。

**Comment by no1xsyzy** [comment]
可以把 ISO 8601 展开成一个 dict，没必要死磕 `R/` 语法，那很明显是强行为了写成一个字符串设计的。
把 `R<times>/<begin>/<interval>/<end>` 展开成 `{"begin": "<begin>", "interval": "<interval>", "end": "<end>", "times": <times>}` 这样，其中没有的就省了。
应该可以兼顾解析，举个比较复杂的例子，超炮 T
```js
{
  episodes: [
    { begin: '2020-01-10T13:00:00.000Z', interval: 'P1W', times: 6 },
    { begin: '2020-02-28T13:00:00.000Z', times: 1 },
    { begin: '2020-03-20T13:00:00.000Z', interval: 'P1W', times: 5 },
    { begin: '2020-04-17T13:00:00.000Z', interval: 'P2W', times: 2 },
    { begin: '2020-05-15T13:00:00.000Z', times: 1 },
    { begin: '2020-05-22T13:00:00.000Z', times: 1 },
    { begin: '2020-07-24T13:00:00.000Z', interval: 'P1W' },
    // ...
  ]
}
```
或者把 times 过个 accumulate() 仍然叫做 episode。

```typescript
type MaybeMultiEpisode = {begin: String, times: 1} | {begin: String, interval: String, times?: Integer};
type Episodes = Array<MaybeMultiEpisode>;
````

**Comment by weizhenye** [comment]
cron 是指明每次循环的时间点，ISO 8601 的循环是指明开始时间和循环的间隔，不太一样。

按我的想法，绝大多数的番剧，是不描述这个字段的，只有放送时间有变更和少量的非每周放送才会描述。

即用户要获取这个信息时，对未描述的番剧，是拿现有的 `begin` 字段和默认为 `P7D` 的 interval 去计算实际放送的星期、时间。

这种情况下，使用 cron 语法的话就会要多写一个解析逻辑。

@no1xsyzy times 应该没啥用，目标信息是番剧最新的放送时间，主要就是靠 begin 和 interval。至于这两个信息是按 ISO 8601 规范 `R/<begin>/<interval>` 还是拆开成两个字段，我个人倾向使用 ISO 8601 规范，感觉上简洁一点，解析上只是多了一步 split。（另个原因是放送变更的 begin 应该叫什么比较难想（

**Comment by wxt2005** [comment]
可能之前说的有些乱了，我这里总结下自己的想法：

现在的共识应该是，周期放送时间应该只保留最新的数据，修改历史对我们这个项目来说没有意义。

那么，我个人认为番组“放送开始时间”和“周期放送时间”这两个东西应该分开，前者理论上是固定的元数据（我甚至认为这个只需要日期，就像bangumi一样），后者才是需要视情况更新的。同时对于站点的放送信息来说，应该只需要后者，什么时候开始放的其实无关紧要。

其次，如果需要加上“周期放送时间”，那建议就是全部加上，而不是只对特例做打补丁式的修改，否则变成要处理两种逻辑，第一次用的人可能不太会注意到会有这么个特殊字段导致处理的遗漏。

最后才是语法问题，我之所以偏向crontab而不是那个循环的间隔，是因为前面提到的“周期放送时间”的开始时间无关紧要，但是如果用这种方式表示，就变成一定得加上开始时间了。

**Comment by weizhenye** [comment]
> 我们对站点放送时间的需求，是为**正在放送**的番剧。

我的观点如上所说，周期放送时间是个时效性数据，向前追溯已完结的番剧去补充这个时间我觉得是没什么价值的。我甚至认为放送结束后删掉也没关系。

放送开始时间如果只有日期的话会有时区问题，在有时间信息的情况下还是应该保留这个信息的。

至于打补丁式的修改，我觉得处理上还是一个逻辑，只是入参两个值有默认值而已。我倒是觉得老用户才可能有遗漏，增加这个字段时，文档里肯定写明周期放送时间的获取方法，然后说这个字段可能为空，对新用户来说 begin 和 broadcast 两个字段是没有先入为主的干扰的，总不会直接对着 `dist/data.json` 去猜含义吧。老用户可能之前已经用 begin 和默认的 P7D 实现了，不了解新出的字段会遗漏。

**Comment by wxt2005** [comment]
>我的观点如上所说，周期放送时间是个时效性数据，向前追溯已完结的番剧去补充这个时间我觉得是没什么价值的。我甚至认为放送结束后删掉也没关系。

虽然是时效性数据，但是放送结束后删掉这个我是反对的，从使用的稳定性上来说也不应该这么干。

> 放送开始时间如果只有日期的话会有时区问题，在有时间信息的情况下还是应该保留这个信息的。

`begin`这个字段就尽量不动了。

> 至于打补丁式的修改，我觉得处理上还是一个逻辑，只是入参两个值有默认值而已。

最后这点其实你说的是用打补丁的方式没问题，确实“也不是不能用”。但是常规来说加字段就应该统一加吧，除非有什么特别明显的坏处才考虑不这么做。语义上也更明确，把两种时间的含义分开了。

**Comment by no1xsyzy** [comment]
我不是特别确定 “周期放送时间只保留最新的数据” 是哪种意思：

1. 只管最新话（last）或者只管最近将来的一话（soonest），能够计算出该话是**第几话**和**何时**播出；
2. 只管它可能在何时播出，而不管在该时是否真的会播出，但保证在其他时间不会播出。

只有第二种才能正常应用 crontab 语法，第一种的话其实也就是 P7D 被换掉，其他部分并不会改变，那么我觉得额外引入 crontab 语法并没有什么方便之处。

或者是否要支持 crontab 的其他语法？比如一月一日从早 6 点整到晚 6 点整每个整点放一集 [`0 6-17 1 1 *`](https://crontab.guru/#5_7-12_1_1_*)，或者每月更两集 [`5,35 18 1 * *`](https://crontab.guru/#5,35_18_1_*_*)。那样的话还行？表义能力强了很多，相应地处理上来说要么就是调用库 / 采用 SaaSS API，要么很麻烦的自写。

**Comment by wxt2005** [comment]
> 只管它可能在何时播出，而不管在该时是否真的会播出，但保证在其他时间不会播出。

我指的是这一种。

事实是，根据我们这份数据来推算已经播出了几话是完全没办法保证准确度的。例如中间停播了几集，差了一集总集篇之类的情况都需要手动处理。

**Comment by weizhenye** [comment]
我没怎么理解你说的「语义上也更明确」。

我整体说一下我的想法，假设周期放送时间这个字段叫 broadcast，那么本次改动的内容为：
1. 正在放送的番剧对象中增加 broadcast 字段
2. 正在放送的 site 对象中增加 broadcast 字段
3. broadcast 字段非 required
4. broadcast 字段格式为 `R/<broadcastBegin>/<interval>`

你前面提到放送开始时间和周期放松时间分开，我是认同的，就是两个字段，原先的 begin 不变，从数据结构定义上两者语义是明确的。

而你说的加字段应该统一加，即字段应该是 required，这个应该是我们主要的分歧点，我觉得是应该看字段实际情况的。现在 `site.url` 和 `site.id` 都不是 required 的，`item.comment` 和 `site.comment` 也不是 required 的（好像是我 #83 改的）。而周期放送时间，如果是 required 要全部加的话，我们看下针对已完结番剧，我们做这次修改实际该怎么操作：
* 如果使用 cron 语法，那取 end 值，按每周放送转换，site.broadcast 没有
* 如果使用 ISO 语法，那取 begin 值，默认间隔为 P7D

这种方式只能覆盖大部分正常放送的 tv 类型番剧，其他的转完都是错误的值，一个字段的值无法保证正确性的情况下，还不如未定义。再者已完结番剧的周期放送时间意义不大，我们也不可能人工地去补完所有番剧的这个字段。

那么就是考虑 required 但是可以为空字符串的情况。你前面提到留空表示非规律放送，这个可能不太能准确描述，已完结番剧我们补充不了这个字段，从实际操作上只能留空，那留空得代表没这个信息，代表未定义。

一个字段是 required 且空字符串代表未定义，与一个字段是 optional 的可以不存在这个字段，我认为从使用上是没什么区别的，用户从文档而不是数据本身来了解数据结构，代码使用时即便是强类型语言也是能正常处理的。从数据分发上，因为会在 site 中增加字段，那 required 就会增加不少的文件大小，仅仅为了代表未定义。

**Comment by wxt2005** [comment]
我之前没有考虑到已完结番组的问题，而是打算只针对正在播放的以及将来添加的番组增加这个字段，毕竟就像你说的，完结之后这个字段已经没有什么意义了。我反对的是用补丁的方式，只针对非周播或者播放时间有变化的番剧加字段。

假定这个字段是optional的。如果这个字段缺失，按你之前提议的补丁方式，就会产生两种含义：

1. 数据暂缺（已完结或者还未确定）
2. 按默认的`begin`+`7D`的方式循环

我的提议是后续的番组只要播放周期确定下来了（不管是番剧本身还是放送站点的），那么就加上`broadcast`字段，不论它是否和`begin`+`7D`推导出来的时间相同，这样就消灭掉了上面说的情况2，避免了歧义。

至于语法，我倒不是非得坚持用cron，ISO也可以接受。

**Comment by weizhenye** [comment]
我理解你的意思了。我原先想着是因为已完结番剧只能留空，而且当前用户已实现的方式就是 begin + P7D，所以新增字段自然就向前兼容，可以有默认行为。你是希望增加这个字段后，用户仅从 broadcast 字段就能获取这个信息。

我觉得对正在放送的番剧都填 broadcast 字段是 OK 的，规范上没填就当作未定义，用户实际面对未定义用什么方式处理是用户自己的行为，规范上不保证。

我主要的点是这个字段从整个数据看来是在特定时间内特定番剧发挥作用的，不希望它是 required 的导致所有的番剧都得加上，大部分还都是只是 `"broadcast": ""` 这样。

**Comment by wxt2005** [comment]
那看起来已经基本上达成一致了。我尝试整理下下个版本要做的修改：

* 针对所有未完结的番组（`end`为空）以及将来添加的番组，增加`item.broadcast`和`item.sites.broadcast`字段，分别用于表示番剧本身的和放送站点的放送周期数据。该数据如果在放送中产生变化（放送周期变更），则直接更新到最新状态。
* `broadcast`为optional。如果缺失，在已完结番组的情况下表示未处理的历史数据，在未完结的情况下表示数据暂缺。
* `broadcast`的格式参考[ISO 8601](https://zh.wikipedia.org/wiki/ISO_8601)的循环时间格式，为`R/<broadcastBegin>/<interval>`。

关于这个`interval`我有个想法，是不是现阶段直接指定几个常用的就行了？比如：

* 一次性：`R1/2020-01-01T13:00:00Z`（要不要写明只循环一次？还是`R/2020-01-01T13:00:00Z`？）
* 周播：`R/2020-01-01T13:00:00Z/P1W`
* 日播：`R/2020-01-01T13:00:00Z/P1D`
* 月播：`R/2020-01-01T13:00:00Z/P1M`

如果真出现特别奇怪的放送规律，再按规范扩展。

**Comment by weizhenye** [comment]
ISO 8601 规范中 interval 部分是必填的，一次性放送的应该是 `R12/2020-01-01T13:00:00Z/P0D` 这样表示，repeat 次数写不写应该都没关系。我觉得统一用 D 就好了，周是 `P7D`，月播其实目前没遇到，不过用 `P1M` 的话可能不太符合实际情况，星期估计还是一样的，是 7 的倍数，得按天来描述。

**Comment by no1xsyzy** [comment]
月播有《卫宫家今天的饭》，确实是 `P1M`，都是在每月 1 号（除了第一话稍微早了不同电视台略有出入的若干天）。确实很少出现。

**Comment by weizhenye** [comment]
哦，看来还是得有 `P1M`。那就按这样来吧，后面遇到奇怪的再讨论扩展。

**Comment by wxt2005** [comment]
嗯，月播肯定是用`P1M`，反而不太可能出现用天记的循环周期。

那现在就是这样：

一次性：`R/2020-01-01T13:00:00Z/P0D`
周播：`R/2020-01-01T13:00:00Z/P7D`
日播：`R/2020-01-01T13:00:00Z/P1D`
月播：`R/2020-01-01T13:00:00Z/P1M`
