### ISSUE TITLE
考虑增加 bangumi-data 用户项目的展示

### ISSUE THREAD

**Issue by weizhenye** [bangumi-data/bangumi-data#107]
例如 [anime-offline-database](https://github.com/manami-project/anime-offline-database#other-projects-using-this-database), [DPlayer](https://github.com/MoePlayer/DPlayer#who-use-dplayer), [Apollo](https://github.com/ctripcorp/apollo#known-users), [Awesome Vue.js](https://github.com/vuejs/awesome-vue#projects-using-vuejs)，形态可以是 README、Wiki、`bangumi-data/awesome` 仓库之类的，加上用户项目的展示。

对用户来说能增加曝光，对我们维护来说能了解具体的使用场景，后面数据格式新增修改时能考虑更全面。

**Comment by wxt2005** [comment]
好主意。不过这个是不是要需要找到作者然后获取许可的？

**Comment by weizhenye** [comment]
无禁止则允许，对项目如实描述，不夸大不虚构，不会有问题的吧。可能一开始添加一些我们知道的项目，后面主要是靠作者自己 PR 添加了。

我们需要定一下具体形态，展示哪些内容。

**Comment by weizhenye** [comment]
我目前想法是建 `bangumi-data/awesome` 仓库，在 `bangumi-data/bangumi-data` README 里加这个仓库的链接。

内容格式大概是：

* [番组放送](https://bgmlist.com/)：方便快捷的版权动画播放地址聚合站 [![GitHub Stars](https://badgen.net/github/stars/wxt2005/bangumi-list?icon=github)](https://github.com/wxt2005/bangumi-list)
* [蜜柑计划](https://mikanani.me/)：新一代的动漫下载站
* [Anime Data](https://anime-data.com/)：可视化地展现各站动画播放数、评论数等数据
* [Bangumi番组计划](https://github.com/czy0729/Bangumi): 一个基于`React-Native`的 Bangumi 第三方客户端 [![GitHub Stars](https://badgen.net/github/stars/czy0729/Bangumi?icon=github)](https://github.com/czy0729/Bangumi)

有没有什么建议，要不要分类什么的

**Comment by wxt2005** [comment]
我觉得没问题，就先这样好了。现在项目少，分类可以先不搞，否则看着孤零零的。
