### ISSUE TITLE
希望以后更新本季番组数据时可以同时更新上一季的番组完结时间数据

### ISSUE THREAD

**Issue by arition** [bangumi-data/bangumi-data#12]
我这里用数据的话需要获取番组是否完结，否则就会将这一番组延续至这一季。所以希望可以同时更新上一季的番组完结时间数据。
我自己也尝试用了一下 [bangumi-data/helper](https://github.com/bangumi-data/helper) ，不过执行```bdh create 201701```时间很长，不知道是否是正常现象……

**Comment by arition** [comment]
```bdh```是我用错了……应该是用```bdh create 2017q1```。已经提交pull request #13 下次还是希望可以一起更新。

**Comment by weizhenye** [comment]
放送结束时间的更新，需要到下个季度的第一天，也就是 1 月番，要 4 月 1 日才能更新。

单纯更新已有的数据时，使用 `bdh update 201701`。

**Comment by arition** [comment]
明白了。close #12

**Comment by weizhenye** [comment]
cal.syoboi.jp 能拿到结束时间的年月，没有日，但有这个字段时，番剧不一定完结了，所以要当前月大于拿到的月，才能保证取到最后一集的时间。

**Comment by weizhenye** [comment]
我自己都记错了，更新放送结束时间还是要用 bdh create 的……
