### ISSUE TITLE
增加港澳台地区放送站点数据

### ISSUE THREAD

**Issue by lintmx** [bangumi-data/bangumi-data#120]
目前 4 月番大陆地区普遍延期播放，建议增加巴哈姆特、木棉花等站点数据。

**Comment by weizhenye** [comment]
当说要增加某个站点时，需要：
1. `*` 提供该站点番剧专辑页面的 url，可以从中识别出 id 部分
2. 提供该站点**所有**番剧的专辑页面 url 获取方法
3. 向 https://github.com/bangumi-data/helper PR 该站的爬爬
4. 每个季度及时执行爬爬，把数据更新到 bangumi-data 中
5. [把该站**所有**番剧更新到 bangumi-data 中](https://github.com/bangumi-data/bangumi-data/issues/11)。大脑放射状光线.png

正写一半发现已经有 #121 了 orz

**Comment by wxt2005** [comment]
我先把动画疯手动加上了，helper那边有空再提PR吧（
