### ISSUE TITLE
我去 弄个TG或者Q群啊 大家一起反馈情报 不然这样数据更新太慢了

### ISSUE THREAD

**Issue by lirener** [bangumi-data/bangumi-data#19]
我去 弄个TG或者Q群啊 大家一起反馈情报 不然这样数据更新太慢了
刚刚还在老的项目反馈……2017年07月的番的时候我就不知道去哪里反馈 别人说来github反馈
我找了没找到 今天算是看到了 这边似乎是最新的？
我之前反馈的地方可以帮我删掉https://github.com/wxt2005/bangumi-list/issues/51
主要反馈内容：
2017年10月的 
つうかあ已经翻译为侧车搭档 由A站独家
黑色五叶草也少了片叶子更名为黑色四叶草...

**Comment by weizhenye** [comment]
已更新

**Comment by lirener** [comment]
@weizhenye 
牙狼 VANISHING LINE更新了是B站拿了好像不过不是独播
http://bangumi.bilibili.com/anime/6468/play#115544

**Comment by lirener** [comment]
@weizhenye 
理想禁区 爱奇艺 搜狐 腾讯 B站都有了……

**Comment by lirener** [comment]
机甲大师 是腾讯拿的有国语和日语版
牙狼B站好像暂时不能看了 估计在买版权...也不懂
