### ISSUE TITLE
希望补充拼音和罗马音

### ISSUE THREAD

**Issue by no1xsyzy** [bangumi-data/bangumi-data#21]
来自下游请求：
https://github.com/wxt2005/bangumi-list/issues/23
https://github.com/wxt2005/bangumi-list/issues/46
建议加到titleTranslate内的字段种类

**Comment by no1xsyzy** [comment]
稍微做了一点搜索，拼音为`zh-Hans-Latn`和`zh-Hant-Latn`，罗马音为`ja-Latn`

另外，说句题外话，其实`zh-*`已经不推荐了，推荐的是`cmn-*`，感觉ISO混进了一个二五仔。

**Comment by weizhenye** [comment]
感觉这个应该是在 bangumi-list 里实现吧？对于中文和日文，应该都会有对应的库直接得到拼音和罗马音，跑在浏览器实时转换都没问题，放在 bangumi-data 维护的话算是冗余信息了。

关于语言标识，选用的是 [BCP47](https://tools.ietf.org/html/bcp47) 规范，`zh-*` 是使用最广泛也应该是推荐的，不推荐来源请求。当时讨论过台湾香港有些译名会不一样，是否应该使用地区标识 `zh-TW`、`zh-HK` 来区分，结论是不必分这么细，直接 `zh-Hant` 就好了。`zh-cmn-*` 这样区分普通话和方言的标识就更细了。

**Comment by weizhenye** [comment]
https://github.com/wxt2005/bangumi-list/pull/49
