### ISSUE TITLE
讨论制定下一版本（v0.2.0）的数据结构

### ISSUE THREAD

**Issue by weizhenye** [bangumi-data/bangumi-data#23]
以下列表作为讨论项（可留言添加）：
1. 支持剧场版、OVA/OAD、Web 动画等类型（详见 #1）
    讨论数据维护方式及字段，可参考 https://github.com/MikanProject/bangumi-data
2. 支持非日本动画（在 #22 提到）
    考虑国产、欧美、中日两版同步放送等情况
3. 番剧页面准入条件（在 #11 提到）
    部分站点的番剧页面只有介绍或 PV，没有实际视频，是否可以添加？
4. 明确各个站点信息字段的改动（在 https://github.com/bangumi-data/bangumi-data/issues/11#issuecomment-334955614 提到）
    * 有些信息无法自动化获取，实际上就是没法用的，考虑删除或默认值为 `null`
    * `lang` 字段的含义
    * 字段增加（如第三条提到的，是否用字段标注有无实际视频）
5. resource.json 中是否用 `{{id}}` 作为模板

**Comment by weizhenye** [comment]
我的想法：

1. 关于番剧类型
    * 在原有数据结构上增加 `type` 字段，枚举值为 `tv`、`web`、`movie`、`ova`
    * 关于各个类型的时间字段
      + `tv` 类型，`begin` 为第一集放送开始时间，`end` 为最后一集放送结束时间。
      + `web` 类型，`begin` 为第一集播放开始时间，`end` 为最后一集播放结束时间。
      + `movie` 类型，`begin` 为上映时间，以上映地点的零点为准（如日本 UTC+9 `2017-11-28` 上映，则值为 `2017-11-27T15:00:00.000Z`），`end` 为 `null`（是否考虑 `begin + 片长`？）。
      + `ova` 类型，`begin` 为第一集发售时间，`end` 为最后一集发售时间，皆以发售地点的零点为准。
    * 数据源可以爬 https://bgm.tv/anime/browser/movie
2. 关于番剧语言
    以动画使用（配音、文本、产地）的语言为准，使用 `lang` 字段标识。如《RWBY》为 `"lang": "en"`，国产中文配音为 `"lang": "zh-Hans"`，国产日配为 `"lang": "ja"`
3. 关于番剧准入条件
    各个站点如果有某一动画的番剧页面，都可以添加。增加 `exist` 字段标明该页面是否有有实际视频。无视频的情况有：版权到期或审查下架、新番组还未放送、站点为 SEO 而单纯添加介绍。
4. 关于站点番剧信息字段
    * `site`：不变。
    * `id`：不变。对有规律的 id，构建流程增加校验。
    * `begin`：不变。未知时为空字符串。
    * `official`：更改。值为 `true`、`false`、`null`。
    * `premuiumOnly`：更改。值为 `true`、`false`、`null`。这个字段有点不太准确，目前会员类型千奇百怪，有些是会员能看，有些是第一个星期要会员可看，一星期后就免费，不太好描述。一个季度完结后还要重新更新一遍才能保持准确。
    * `censored`：删除。这个信息无法自动化获取，人工填写也需要看过才知道，基本无法维护。
    * `lang`：删除。这个字段当时定义的时候，是为了「[预留以后可能引入英文放送站的可能性](https://github.com/wxt2005/bangumi-list/issues/39#issuecomment-233159871)」。这个信息应该是描述站点在放送某番剧时，所使用的（字幕）语言，应该是属于站点这一层级（`data/sites/onair.json`）而不是番剧的。有特例是，B 站某些番剧只供港澳台，那应该用 `"lang": "zh-Hant"` 描述，但它不会同时有两个番剧页面；又如创世京紫七国语言，我没上过 Netflix 不太清楚，应该是在一个页面内，可以切换各个语言，那这个字段就不知道写什么了。干脆删除。
    * `comment`：不变。
    * `exist`：新增。值为 `true`、`false`、`null`。描述是否有视频。

**Comment by wxt2005** [comment]
基本同意上面列出来的修改想法。
我这里有个问题，就是关于 `id` 这个字段，你提到的“ 对有规律的 id，构建流程增加校验“是指什么？现在以番组出现在元数据中的数组 index 来构建 id 有些不太稳定，很容易出现变更的情况（除非保证新数据只能 append 在数组末尾），在实际使用中似乎意义不大。

**Comment by arition** [comment]
1. 支持剧场版、OVA/OAD、Web 动画等类型（详见 #1）
我建议针对剧场版新增一个 BD 发售日期的字段，因为大多数字幕组只有拿到 BD 后才能做字幕，发布 Rip，只提供日本上映日期是没啥意义的。另外是不是对剧场版还考虑加入海外上映日期？
2. 支持非日本动画（在 #22 提到）
可以，做好语言区分就行
3. 番剧页面准入条件（在 #11 提到）
可以
4. 明确各个站点信息字段的改动（在 #11 提到）
我不建议删除 ```censored``` 等字段，就算暂时没法维护也不应该删掉。如果不清楚是不是有 censor，可以考虑使用一个 ```unknown``` 或者直接用 ```null```  
站点的 ```lang``` 我认为可以删掉，这个确实意义不明  


还有一个额外的问题，针对资源站（```resource.json```），是否可以用```{{id}}```作为模板？因为像蜜柑计划这样的区分番组的的资源站，直接填```id```肯定更准确

**Comment by weizhenye** [comment]
@wxt2005
我说的 id 字段是指站点信息里的，如 https://github.com/bangumi-data/bangumi-data/blob/v0.1.76/data/items/2017/10.json#L1128 这个 id 可以加验证规则。你说的 id 是构建后与 title 字段平级的那个自动生成的 id 吧，感觉没什么用，是不是可以直接删了。

@arition 
关于 BD 发售日期，我观点是不添加。在 meta 信息里面，`title`、`titleTranslate`、`lang` 和 `type` 是描述番剧本身属性，通过这些信息可以定位一个番剧；`officialSite` 字段，最早讨论时我提出放到 `sites` 数组里，因为它比较特殊所以放 meta 里；`begin` 和 `end` 字段，用于组织、分类整个数据集。以上信息都是所有类型番剧都有的。对于 BD 发售日期，非日漫可能都没有，如果给剧场版加了，那 TV 是不是也要加，还要变成一个数组，还有 DVD 啥的。如果加了 BD 发售日期，那 meta 信息的界限在哪里，监督、制作公司等 wiki 类的信息是不是也能加。我觉得，bangumi-data 的定位是提供一部番剧相关的站点信息，wiki 类的信息不是主要功能。每个项目使用 bangumi-data 的目的都会不同，需求也不同，绝大多数是有一个构建流程的，bangumi-data 给出了 Bangumi.tv 的信息，有人贡献的话 myanimelist、anidb 也能加，如果要 wiki 类信息，可以根据项目需求在构建流程去爬来自己存着。我觉得 bangumi-data 本身应该保持精简。

`censored` 想了想保留也可以。

`resource.json` 我赞同使用 `{{id}}`。

**Comment by wxt2005** [comment]
@weizhenye 确实，这个 id 没啥用，删了吧。

**Comment by arition** [comment]
@weizhenye 我觉得对于剧场版/OVA来说，BD发售时间是比较特殊的。国内的用户不可能去日本的剧场版观看，所以日本本土的上映日期对大部分用户来说是毫无意义的，只有等到BD发售了以后才能看到。所以BD发售时间相当于TV的开始播放时间，应该作为番剧相关的信息添加。对于TV来说，BD发售日期并不是必要信息，可添加可不添加；但是剧场版的BD发售时间是至关重要的，还是加上比较好。

**Comment by weizhenye** [comment]
@arition 对于蜜柑计划这样面向国内用户的资源站，上映时期是没什么用，这个我认同，但这个是你的需求；如果我想基于 bangumi-data 做一个动画播放数据的制作公司的排行，那制作公司这个信息对我很重要，是不是也可以添加？我想表达的是，对 bangumi-data 本身来说，BD 发售时间并不是一个为描述清楚一部番剧而必有的属性，它是因项目而异的。

**Comment by wxt2005** [comment]
那看来数据结构这块大家没有什么异议了，现在主要的争论点在于要不要加 BD 发售时间。我个人其实倾向于是不加的，现阶段这个数据源的主要还是专注于收集番组在国内站点上的放送时间信息，对其它信息而言，有比我们做的更好的数据源，没有必要重复维护。

**Comment by weizhenye** [comment]
以上总结：

```js
Lang: "ja" | "en" | "zh-Hans" | "zh-Hant"
BangumiType: "tv" | "web" | "movie" | "ova"
SiteName: "acfun" | "bangumi" | "bilibili" | "dmhy" | "iqiyi" | "kankan" | "letv" | "mgtv" | "nyaa" | "pptv" | "qq" | "saraba1st" | "sohu" | "tucao" | "tudou" | "youku"
```

```js
{
  // 站点元信息
  "sites": {
    SiteName: {
      // 站点标题
      "title": String,
      // 站点番剧页面 url 模板，`{{id}}` 为替换部分
      "urlTemplate": URL
    }
  },
  "items": [
    {
      // 原始标题
      "title": String,
      // 标题翻译
      "titleTranslate": {
        Lang: [
          String
        ]
      },
      // 番剧类型
      "type": BangumiType,
      // 番剧语言
      "lang": Lang,
      // 官方网站
      "officialSite": URL,
      // tv 放送开始、web 播放开始、movie 上映零点、ova 发售开始
      "begin": Date,
      // tv 放送结束、web 播放结束、movie 上映零点+时长、ova 发售结束
      "end": Date,
      // 备注
      "comment": String,
      // 站点信息
      "sites": [
        {
          // 站点名称 id
          "site": SiteName,
          // 番剧页面 id
          "id": String,
          // 播放开始
          "begin": Date,
          // 是否官方版权所有
          "official": Boolean | Null,
          // 是否需要会员
          "premuiumOnly": Boolean | Null,
          // 是否有审查、删减
          "censored": Boolean | Null,
          // 是否有实际视频
          "exist": Boolean | Null,
          // 备注
          "comment": String
        }
      ]
    }
  ]
}
```

另外关于站点元信息，字段名 `sites` 一个复数给人感觉是个数组，是不是改成 `siteMeta` 比较好？还有站点的类型 `onair`、`info`、`resource`，这个[当时](https://github.com/wxt2005/bangumi-list/issues/39#issuecomment-237737582)讨论时是有的，我说它冗余是放在 items 里算冗余，构建后 siteMeta 里应该还是要有吧？

**Comment by arition** [comment]
现在的```sites```是把以前的```resource```，```onair```和```info```整合了吗，我觉得整合了以后```sites```还是需要加上站点类型的

**Comment by weizhenye** [comment]
站点元信息里的 type 是我看错了，构建后 `dist/data.json` 里现在就是有的。

**Comment by wxt2005** [comment]
我同意改成 `siteMeta`。不过这样改我觉得得升个 major 版本了，完全不兼容了吧

**Comment by weizhenye** [comment]
在主版本号为 0 的时候，改变次版本号就表示包含了 breaking change，这个是 semver 本身的规则，npm 安装依赖也是遵守这个规则，使用 0.2.0 没问题的。

**Comment by wxt2005** [comment]
OK，没问题。
