### ISSUE TITLE
能不能添加唯一ID?

### ISSUE THREAD

**Issue by swearl** [bangumi-data/bangumi-data#29]
方便找到对应记录进行更新.

**Comment by weizhenye** [comment]
从数据结构约定上，v0.2.0 已经去掉了 id

从实践上，目前可以用 Bangumi ID 加 `lang` 字段作为唯一标识

**Comment by swearl** [comment]
那是不是每一个番,就一定会有bangumi id?

**Comment by weizhenye** [comment]
数据结构上没有约定必须有 Bangumi ID，但目前已存在的都是有的
