### ISSUE TITLE
针对多版本番剧特例的处理方式

### ISSUE THREAD

**Issue by XinoAssassin** [bangumi-data/bangumi-data#32]
本次四月番中出现了一部重庆机甲，多家视频网站均提供了双版本，一版为日语配音一版为中文配音：
- bilibili: ja: https://bangumi.bilibili.com/anime/23811, zh: https://bangumi.bilibili.com/anime/23919
- iqiyi: http://www.iqiyi.com/a_19rrh1tbu5.html 页面下有双版本
- qq: ja: http://v.qq.com/detail/e/e3yh815x8vf82oi.html, zh: http://v.qq.com/detail/2/225pc9y4ogg0pqq.html
请问这个特例的处理方式

**Comment by weizhenye** [comment]
添加两条，`lang` 分别为 `ja` 和 `zh-Hans`。不过目前已有的国漫都没区分的，也是待改。

**Comment by XinoAssassin** [comment]
了解，之后我加网飞的内容的时候看看国漫一起改了吧。

**Comment by markni** [comment]
lang应该考虑移动到sites meta里，或者支持override，这样不会有重复条目
