### ISSUE TITLE
翻译中`第二季`和`第2季`能否同时存在?

### ISSUE THREAD

**Issue by Trim21** [bangumi-data/bangumi-data#46]
准备把爱奇艺的官方翻译加到番剧的翻译中,遇到了这么一个问题- -询问一下

**Comment by weizhenye** [comment]
我感觉同时存在没什么问题，虽然也可以脚本保证只有其中一种。
@wxt2005 觉得呢？

**Comment by XinoAssassin** [comment]
我觉得可以同时存在，17年10月开始的大部分中文翻译除了Bangumi的翻译外，站点的翻译如果不同也是被纳入了数组的。
