### ISSUE TITLE
添加B站仅限港澳台的番剧编号？

### ISSUE THREAD

**Issue by upsuper** [bangumi-data/bangumi-data#54]
现在有部分新番在B站上是仅限港澳台或者仅限台湾的，这些或许也应该加入到数据中去（特别是考虑到连nico和netflex都有了）。

数据里面B站的链接是 `https://bangumi.bilibili.com/anime/*` 的形式，但看起来现在B站的番剧地址都是 `https://www.bilibili.com/bangumi/media/md*` 而且两者的编号还不一样，不是很确定如何查到anime那个编号……

**Comment by weizhenye** [comment]
目前 B 站的番，只有港澳台的，是已经有加进来了，可能有漏；同时有港澳台和大陆的，是只加了大陆的。对于同时有的情况，需要加港澳台吗？

`/anime/*` 的是大概半年前的情况，现在 B 站 xjb 改成 `/bangumi/media/md*` 并做了跳转。目前还可以在[番剧索引](https://bangumi.bilibili.com/anime/index#p=1&v=0&area=2&stat=0&y=0&q=0&tag=&t=0&sort=0)找到 `/anime/*` 格式。如果要切换的话，要等 Bangumi Data 的下个大版本了（不知道什么时候）。或许目前先可以在 [helper](https://github.com/bangumi-data/helper) 里同时支持这两种格式，数据保留 `/anime/*` 格式的。

**Comment by weizhenye** [comment]
不太清楚 B 站对区域限定番的显示策略。

另外大致找了下，可以通过 `https://bangumi.bilibili.com/view/web_api/media?media_id=102692` 返回的 `result.param.season_id` 获取到 `/anime/*` 格式。我等会给 helper 加下功能。

**Comment by weizhenye** [comment]
#126
