### ISSUE TITLE
"忍者乱太郎 4期"的结束日期不对...

### ISSUE THREAD

**Issue by Trim21** [bangumi-data/bangumi-data#64]
1996-09-31T09:00:00.000Z
这个不在检查脚本检查的范围之内吗（

**Comment by weizhenye** [comment]
惊了，[Joi](https://github.com/hapijs/joi/blob/v13.6.0/lib/types/date/index.js#L14) 没校验到这种情况

**Comment by Trim21** [comment]
用其他语言parser的时候报了日期超出范围...
