### ISSUE TITLE
通过视频时长判断是否被和谐

### ISSUE THREAD

**Issue by arition** [bangumi-data/bangumi-data#70]
一般的番组都会有标准的时长。现在许多视频站直接有片段被剪掉了，导致时长不一致。是否可以通过这个标志来标识censored属性？

**Comment by Trim21** [comment]
不能

下载器会返回给rpc调用者的只有文件大小，没有视频时长

**Comment by Trim21** [comment]
抱歉，一大早没睡醒, 弄错了…

**Comment by arition** [comment]
B站的话，只要有对应的cid和aid，就可以通过
```https://interface.bilibili.com/player?id=cid:57467566&aid=32836144```
这样的url来获取视频长度信息

**Comment by no1xsyzy** [comment]
B站还会出现专供版，时长一致……
也就是说时长不一致蕴含和谐，但反之不然

**Comment by weizhenye** [comment]
ED Card 塞个 5 秒就没法判断了

**Comment by arition** [comment]
@no1xsyzy 可以先把确定和谐的挑出来啊，至少可以确定这一部分是确定和谐的了

**Comment by arition** [comment]
@weizhenye 现在好像还没有有edcard的官方源吧。而且5秒完全可以算作是误差，可以取相差10秒以上的番组作为确定和谐的番组

**Comment by weizhenye** [comment]
@arition 

我不认为仅根据视频时长就可以判断是否和谐。如果以 TV 放送源作为标准，先不说怎么获取 TV 源的视频长度，TV 源本身就会有差异，有些番 AT-X 尺度大点，有些番不同电视台长度不同（有无预告、有无 ED Card 等）。到版权站后，提供的版本与 TV 源不一致的可能性更大了，有些抹去了 OP 后的赞助，有些加了大陆专属的广告（爱吃拉面的小泉）。

我在 Bangumi 点格子时看到章节信息没全的[都会补上](https://bgm.tv/user/woozy/wiki/ep)，填时间信息时遇到相差 30 秒的情况很多，而且是每集都相差 30 秒，并不是内容少了，就是赞助、预告、ED Card 等部分。

这个判断条件再具体到各个番剧各个站点，就会有更多奇怪的情况，比如 RE0 第一集 48 分钟，优酷分成了 01A、01B 两集；有些旧番传的是 BD 源，与判断条件的「标准时长」又有差异；有些番上来很黄很暴力，过几天站方怂了剪掉几分钟（如果有妹）。

最终搞下来得到一个 probablyCensored 的值，我觉得是没什么用的。反而把不确定的值与目前人工判断的正确的值混在一起会导致正确的也变得不可靠了，虽然没多少。

我是觉得，如果无法保证它的正确性，宁愿没有。
