### ISSUE TITLE
讨论下一版本 v0.3

### ISSUE THREAD

**Issue by weizhenye** [bangumi-data/bangumi-data#77]
`v0.2` 发布已经有一年了，期间不少站点有了变化，我个人在维护中也有些想法。

1. **是否考虑删除所有土豆的数据？**
2. **是否考虑删除所有看看的数据？**
3. **是否考虑删除所有 AcFun 的旧数据，urlTemplate 更换为新的专辑页？**
urlTemplate 从 `http://www.acfun.cn/v/ab{{id}}` 变更为 `http://www.acfun.cn/bangumi/aa{{id}}`。
4. **是否考虑把 Bilibili 的 urlTemplate 更换为新的专辑页？**
urlTemplate 从 `https://bangumi.bilibili.com/anime/{{id}}` 变更为 `https://www.bilibili.com/bangumi/media/md{{id}}/`。
5. **是否考虑删除站点信息里的 official、premuiumOnly、censored、exist、comment 字段？**

**Comment by weizhenye** [comment]
我的选择和理由：

1. 删除。土豆已经转型了，以前所有的链接都 404 了。况且之前优土合并，每份土豆的数据应该都对应了一份优酷的数据。
2. 删除。天天看看（迅雷）已经没有自家的动画了，所有的专辑页列出的播放源都是其他站点的，而且原先买的版权番（如[偶像大师 灰姑娘女孩](http://movie.kankan.com/movie/87458)）也都已经没了。
3. 删除并更换。AcFun 出了新的专辑页，原先的链接都 404 了。
4. 更换。Bilibili 出了新的专辑页，原先的链接都做了跳转，依然可以访问。虽然使用 bdh 来维护的情况下换不换没什么关系，但对于了解不多的热心路人会比较困扰，很难获得原先的专辑页地址。
5. 删除。这些字段都不是「静态」信息。official 会变，版权有期限；premuiumOnly 无法描述实际场景，有些需要会员，有些一周后免费，另外单词拼错应为 premium；censored 只能靠人工判断，且受政策、舆论影响；exist 我当时为什么要加呢，数据有效性问题应该根据约定规范在开发态解决就行了；comment 基本就没用到过。这些字段大多都无法保证正确性，更重要的是，**它们没有被实际使用**。当年在设计中描绘理想，如今在维护中面临现实，为什么要花时间去维护这些没有被使用的字段？现在有 bangumi-data-helper 的情况下，就仅仅在新增的时候跑一下，后续再也不管它们正确与否，要是没有 bdh，那就更不会人来填写、维护它们了。我乐于维护 bdh，将繁琐的工作自动化，但不太想把时间浪费于无意义的产出。我不否认这些字段的价值，在能保证时效和正确性的前提下。它们适合在应用中做成「服务」，不适合在 Bangumi Data 中作为「数据」。

**Comment by swearl** [comment]
支持更新urlTemplate

**Comment by XinoAssassin** [comment]
comment 可以留一下，或者增加一个 region 字段。
在版权地区分隔化越来越严重的今天，有个区域字段来提示哪个区可见对于某些网站来比较实用，例如网飞还有B站港澳台等。
其他的修改基本认同，不过 exist 可以留着。

**Comment by Teachoc** [comment]
请问 Bilibili 新老 id 是否有转换的方法，v0.3 版本使用新 id 后无法通过 哔哩哔哩动画UWP版 的协议（bilibili://bangumi/season/<seasonid>）打开番剧详情页且开发者回复无法通过 mediaId 得到番剧信息。

**Comment by weizhenye** [comment]
`GET https://bangumi.bilibili.com/view/web_api/media?media_id={mediaId}`
返回的 `json.result.param.season_id` 可取到 seasonId
