### ISSUE TITLE
B 站抓取时间有误

### ISSUE THREAD

**Issue by no1xsyzy** [bangumi-data/bangumi-data#88]
显著例子：https://github.com/bangumi-data/bangumi-data/blob/master/data/items/2019/10.json#L239

这时间不太对吧，[第一话](https://www.bilibili.com/bangumi/play/ep285220) 的最早评论是 2019-10-02T24:30:00.000+08:00 也就是 2019-10-02T16:30:00.000Z，也符合番剧页所称的 “周四00:30”。
这个 0918 的，是 [PV](https://www.bilibili.com/bangumi/play/ep284351) 的发布日期。

**Comment by weizhenye** [comment]
fixed in v0.3.6
