### ISSUE TITLE
1997_09_0 的 bangumi id 错了

### ISSUE THREAD

**Issue by alanoy** [bangumi-data/bangumi-data#9]
如题，应该是：9266

**Comment by alanoy** [comment]
1991_10_4 也错了，不重开 issue 了，应该是：210271

**Comment by weizhenye** [comment]
呃，下手太快了，要不你发个 PR 吧，仅仅修改 `data/items/` 目录下对应的数据。

**Comment by alanoy** [comment]
嗯，已发 PR，这个就 close 掉了
