### ISSUE TITLE
iqiyi 链接格式发生更改

### ISSUE THREAD

**Issue by outloudvi** [bangumi-data/bangumi-data#92]
示例：<https://web.archive.org/web/20200213025312/https://www.iqiyi.com/a_19rrh9uqb5.html>。
现时其链接格式似乎为 https://www.iqiyi.com/lib/m_<kbd>id</kbd>.html 。
示例：<https://www.iqiyi.com/lib/m_215660814.html>

**Comment by weizhenye** [comment]
没有。你给的示例版权到期所以 404 了。

后者链接一直都有，不是真实的专辑页面，而是为了 SEO （猜的）开的信息页，实际视频内容不一定在 iqiyi 自己这里，比如你给的示例就是跳到 AcFun 的。
